
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace APIKN
{

using System;
    using System.Collections.Generic;
    
public partial class TUsuario
{

    public long ConUsuario { get; set; }

    public string Identificacion { get; set; }

    public string Nombre { get; set; }

    public string Correo { get; set; }

    public string Contrasenna { get; set; }

    public bool Estado { get; set; }

    public long ConProvincia { get; set; }

    public long ConRol { get; set; }



    public virtual TProvincia TProvincia { get; set; }

    public virtual TRol TRol { get; set; }

}

}
